./build/bin/test_all ./dataset/Yelp.smtx  ./dataset/Yelp.cugraph_reorder 32
./build/bin/test_all ./dataset/Flickr.smtx  ./dataset/Flickr.cugraph_reorder 32
./build/bin/test_all ./dataset/AIFB.smtx  ./dataset/AIFB.cugraph_reorder 32
./build/bin/test_all ./dataset/BGS.smtx  ./dataset/BGS.cugraph_reorder 32
./build/bin/test_all ./dataset/AM.smtx  ./dataset/AM.cugraph_reorder 32
./build/bin/test_all ./dataset/MUTAG.smtx  ./dataset/MUTAG.cugraph_reorder 32
./build/bin/test_all ./dataset/AmazonCoBuyComputer.smtx  ./dataset/AmazonCoBuyComputer.cugraph_reorder 32
./build/bin/test_all ./dataset/AmazonCoBuyPhoto.smtx  ./dataset/AmazonCoBuyPhoto.cugraph_reorder 32
./build/bin/test_all ./dataset/CoauthorCS.smtx  ./dataset/CoauthorCS.cugraph_reorder 32
./build/bin/test_all ./dataset/CoauthorPhysics.smtx  ./dataset/CoauthorPhysics.cugraph_reorder 32
./build/bin/test_all ./dataset/arxiv.smtx  ./dataset/arxiv.cugraph_reorder 32
./build/bin/test_all ./dataset/collab.smtx  ./dataset/collab.cugraph_reorder 32
./build/bin/test_all ./dataset/ddi.smtx  ./dataset/ddi.cugraph_reorder 32
./build/bin/test_all ./dataset/ppa.smtx  ./dataset/ppa.cugraph_reorder 32
./build/bin/test_all ./dataset/products.smtx  ./dataset/products.cugraph_reorder 32
./build/bin/test_all ./dataset/protein.smtx  ./dataset/protein.cugraph_reorder 32
./build/bin/test_all ./dataset/reddit.smtx  ./dataset/reddit.cugraph_reorder 32


./build/bin/test_all ./dataset/Yelp.smtx  ./dataset/Yelp.cugraph_reorder 64
./build/bin/test_all ./dataset/Flickr.smtx  ./dataset/Flickr.cugraph_reorder 64
./build/bin/test_all ./dataset/AIFB.smtx  ./dataset/AIFB.cugraph_reorder 64
./build/bin/test_all ./dataset/BGS.smtx  ./dataset/BGS.cugraph_reorder 64
./build/bin/test_all ./dataset/AM.smtx  ./dataset/AM.cugraph_reorder 64
./build/bin/test_all ./dataset/MUTAG.smtx  ./dataset/MUTAG.cugraph_reorder 64
./build/bin/test_all ./dataset/AmazonCoBuyComputer.smtx  ./dataset/AmazonCoBuyComputer.cugraph_reorder 64
./build/bin/test_all ./dataset/AmazonCoBuyPhoto.smtx  ./dataset/AmazonCoBuyPhoto.cugraph_reorder 64
./build/bin/test_all ./dataset/CoauthorCS.smtx  ./dataset/CoauthorCS.cugraph_reorder 64
./build/bin/test_all ./dataset/CoauthorPhysics.smtx  ./dataset/CoauthorPhysics.cugraph_reorder 64
./build/bin/test_all ./dataset/arxiv.smtx  ./dataset/arxiv.cugraph_reorder 64
./build/bin/test_all ./dataset/collab.smtx  ./dataset/collab.cugraph_reorder 64
./build/bin/test_all ./dataset/ddi.smtx  ./dataset/ddi.cugraph_reorder 64
./build/bin/test_all ./dataset/ppa.smtx  ./dataset/ppa.cugraph_reorder 64
./build/bin/test_all ./dataset/products.smtx  ./dataset/products.cugraph_reorder 64
./build/bin/test_all ./dataset/protein.smtx  ./dataset/protein.cugraph_reorder 64
./build/bin/test_all ./dataset/reddit.smtx  ./dataset/reddit.cugraph_reorder 64


./build/bin/test_all ./dataset/Yelp.smtx  ./dataset/Yelp.cugraph_reorder 128
./build/bin/test_all ./dataset/Flickr.smtx  ./dataset/Flickr.cugraph_reorder 128
./build/bin/test_all ./dataset/AIFB.smtx  ./dataset/AIFB.cugraph_reorder 128
./build/bin/test_all ./dataset/BGS.smtx  ./dataset/BGS.cugraph_reorder 128
./build/bin/test_all ./dataset/AM.smtx  ./dataset/AM.cugraph_reorder 128
./build/bin/test_all ./dataset/MUTAG.smtx  ./dataset/MUTAG.cugraph_reorder 128
./build/bin/test_all ./dataset/AmazonCoBuyComputer.smtx  ./dataset/AmazonCoBuyComputer.cugraph_reorder 128
./build/bin/test_all ./dataset/AmazonCoBuyPhoto.smtx  ./dataset/AmazonCoBuyPhoto.cugraph_reorder 128
./build/bin/test_all ./dataset/CoauthorCS.smtx  ./dataset/CoauthorCS.cugraph_reorder 128
./build/bin/test_all ./dataset/CoauthorPhysics.smtx  ./dataset/CoauthorPhysics.cugraph_reorder 128
./build/bin/test_all ./dataset/arxiv.smtx  ./dataset/arxiv.cugraph_reorder 128
./build/bin/test_all ./dataset/collab.smtx  ./dataset/collab.cugraph_reorder 128
./build/bin/test_all ./dataset/ddi.smtx  ./dataset/ddi.cugraph_reorder 128
./build/bin/test_all ./dataset/ppa.smtx  ./dataset/ppa.cugraph_reorder 128
./build/bin/test_all ./dataset/products.smtx  ./dataset/products.cugraph_reorder 128
./build/bin/test_all ./dataset/protein.smtx  ./dataset/protein.cugraph_reorder 128
./build/bin/test_all ./dataset/reddit.smtx  ./dataset/reddit.cugraph_reorder 128